float4 main(float2 uv : TEXCOORD0, float4 tint : COLOR0,
            uniform sampler2D image : TEXUNIT0, uniform sampler2D rule : TEXUNIT1,
            uniform float4 effect) : COLOR {
    float4 c = tex2D(image, uv);
    float vague = max(effect.z, 0.0039215686);
    float threshold = effect.y * (1+vague)-vague;
    c.a *= smoothstep(threshold,threshold+vague,tex2D(rule,uv).r);
    c *= tint;
    return float4(c.rgb * c.a, c.a);
}
