float4 main(float2 uv : TEXCOORD0, float4 tint : COLOR0, float2 pixel : TEXCOORD1,
            uniform sampler2D image : TEXUNIT0,
            uniform sampler2D rule : TEXUNIT1,
            uniform float4 effect, uniform float4 clipRect) : COLOR {
    float4 c = tex2D(image, uv);
    if (effect.x > 0.5) {
        float mask = tex2D(rule, uv).r;
        float vague = max(effect.z, 0.0039215686);
        float threshold = effect.y * (1+vague)-vague;
        c.a *= smoothstep(threshold,threshold+vague,mask);
    }
    c *= tint;
    c.a *= step(clipRect.x,pixel.x)*step(clipRect.y,pixel.y)*
           (1-step(clipRect.z,pixel.x))*(1-step(clipRect.w,pixel.y));
    return float4(c.rgb * c.a, c.a);
}
