uniform sampler2D samplerFore : TEXUNIT0;
uniform sampler2D samplerMask : TEXUNIT1;
uniform sampler2D samplerUser : TEXUNIT3;
uniform float4 art_clip;
uniform float  alpha;
uniform float3 colorMultiply;
uniform float  maskTransitionVague;
uniform float  maskTransitionStep;
uniform float  ax;
uniform float  ay;
uniform float  size;
uniform float  fade;
float4 main(float2 texCoord1:TEXCOORD0,float4 tint:COLOR0,float2 pixel:TEXCOORD1):COLOR {
float2 texCoord0=texCoord1; float4 result=float4(0,0,0,0);

	float4 mask = tex2D(samplerMask, texCoord1);
	float2 uv = texCoord1;
	float2 cent = float2(ax, ay);			
	float2 poss = uv - cent;				
	float dist = length(poss);				
	float factor = size / 8.0 * dist;		

	float ave = 1.0 / 8.0;					

	float4 fadd = 0;
	float4 fore = tex2D(samplerFore, texCoord1);
	fadd += tex2D(samplerFore, poss * (1.0 - factor * 1.0) + cent) * ave;
	fadd += tex2D(samplerFore, poss * (1.0 - factor * 2.0) + cent) * ave;
	fadd += tex2D(samplerFore, poss * (1.0 - factor * 3.0) + cent) * ave;
	fadd += tex2D(samplerFore, poss * (1.0 - factor * 4.0) + cent) * ave;
	fadd += tex2D(samplerFore, poss * (1.0 - factor * 5.0) + cent) * ave;
	fadd += tex2D(samplerFore, poss * (1.0 - factor * 6.0) + cent) * ave;
	fadd += tex2D(samplerFore, poss * (1.0 - factor * 7.0) + cent) * ave;
	fore *= (ave + (1.0 - ave) * (1.0 - fade));
	fore += fadd * fade;

	float mask_a = mask.a;
	fore.a   *= mask_a * alpha;
	result = fore;

float cover=step(art_clip.x,pixel.x)*step(art_clip.y,pixel.y)*(1-step(art_clip.z,pixel.x))*(1-step(art_clip.w,pixel.y));
return result*cover;
}
