uniform sampler2D samplerFore : TEXUNIT0;
uniform sampler2D samplerMask : TEXUNIT1;
uniform sampler2D samplerUser : TEXUNIT3;
uniform float4 art_clip;
uniform float  alpha;
uniform float3 colorMultiply;
uniform float  maskTransitionVague;
uniform float  maskTransitionStep;
uniform float  param;
float4 main(float2 texCoord1:TEXCOORD0,float4 tint:COLOR0,float2 pixel:TEXCOORD1):COLOR {
float2 texCoord0=texCoord1; float4 result=float4(0,0,0,0);


	float4 fore = tex2D(samplerFore, texCoord1);
	float4 user = tex2D(samplerUser, texCoord1);
	float4 mask = tex2D(samplerMask, texCoord1);
	float mask_a = mask.a;
	float fore_a = fore.a * (1.0 - user.a) + user.a;

	user.r = max(fore.r, user.r);
	user.g = max(fore.g, user.g);
	user.b = max(fore.b, user.b);
	fore.rgb = (fore.rgb * fore.a * (1.0 - user.a) + user.rgb * user.a) / fore_a * param;
	fore.a  *= mask_a * alpha;

	result = fore;

float cover=step(art_clip.x,pixel.x)*step(art_clip.y,pixel.y)*(1-step(art_clip.z,pixel.x))*(1-step(art_clip.w,pixel.y));
return result*cover;
}
