uniform sampler2D samplerFore : TEXUNIT0;
uniform sampler2D samplerMask : TEXUNIT1;
uniform sampler2D samplerUser : TEXUNIT3;
uniform float4 art_clip;
uniform float  alpha;
uniform float3 colorMultiply;
uniform float  maskTransitionVague;
uniform float  maskTransitionStep;
uniform float  centerx;
uniform float  centery;
uniform float  radius;
uniform float  ratio;
uniform float  thick;
float4 main(float2 texCoord1:TEXCOORD0,float4 tint:COLOR0,float2 pixel:TEXCOORD1):COLOR {
float2 texCoord0=texCoord1; float4 result=float4(0,0,0,0);


	float4 mask = tex2D(samplerMask, texCoord1);
	float mask_a = mask.a;

	float2 uv = texCoord1;


	float y = (uv.y - 0.5) * ratio + 0.5;
	float2 zoomuv = float2(uv.x, y);

	float2 ct = float2(centerx, centery);


	float r = distance(ct, zoomuv);
	float r1 = r - radius;
	float r2 = r1 - thick;

	float4 fore = tex2D(samplerFore, uv);


	float a1 = smoothstep(r1, r1 - 0.001, 0.0);
	float a2 = smoothstep(r2, r2 + 0.001, 0.0);
	fore.rgb += (a1 * a2) * 0.5;


	fore.a *= mask_a * alpha;

	result = fore;

float cover=step(art_clip.x,pixel.x)*step(art_clip.y,pixel.y)*(1-step(art_clip.z,pixel.x))*(1-step(art_clip.w,pixel.y));
return result*cover;
}
