// Run from the repository root after compiling with a native C++17 compiler.
// Uses the same font, stb rasterizer, sizes and advance rounding as menu.cpp.
#define STB_TRUETYPE_IMPLEMENTATION
#include "../vendor/stb/stb_truetype.h"
#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <fstream>
#include <iterator>
#include <stdexcept>
#include <string>
#include <vector>

struct Label { const char* text; int size; };
const Label labels[]={{"游戏菜单",28},{"○ 确认   × 返回   ↑↓ 选择",20},
    {"存档",24},{"读档",24},{"快速存档",24},{"快速读档",24},
    {"设置",24},{"历史记录",24},{"自动播放",24},{"返回游戏",24},
    {"字号设置",28},{"覆盖游戏字号",24},{"姓名字号",24},{"剧情字号",24},
    {"恢复默认",24},{"保存并返回",24},{"开",24},{"关",24},
    {"100% 为游戏原字号",20},{"←→ 调整  ○ 确认  × 取消",20},{"保存失败，请重试",20},
    {"0",24},{"1",24},{"2",24},{"3",24},{"4",24},{"5",24},{"6",24},{"7",24},{"8",24},{"9",24},{"%",24},{"字号设置",24}};
struct Glyph { std::vector<uint8_t> pixels; int x,y,w,h; };
struct Region { int x,y,w,h,left,top; };
uint32_t decode(const unsigned char*& p) {
    uint32_t c=*p++; if(c<128)return c;
    unsigned n=(c&0xe0)==0xc0?1:(c&0xf0)==0xe0?2:3;
    c&=(1u<<(6-n))-1; while(n--)c=(c<<6)|(*p++&63); return c;
}
int main(int argc,char** argv) {
    if(argc!=3){std::fprintf(stderr,"usage: bake-fallback-menu output.hpp preview.pgm\n");return 2;}
    std::ifstream f("host/assets/menu.ttf",std::ios::binary);
    std::vector<uint8_t> font((std::istreambuf_iterator<char>(f)),{}); stbtt_fontinfo face{};
    if(font.empty()||!stbtt_InitFont(&face,font.data(),stbtt_GetFontOffsetForIndex(font.data(),0)))return 3;
    constexpr int width=512,height=256;
    std::vector<uint8_t> atlas(width*height); std::vector<Region> regions;
    int ax=1,ay=1,row=0;
    for(auto label:labels) {
        const float scale=stbtt_ScaleForPixelHeight(&face,float(label.size));
        const auto* p=reinterpret_cast<const unsigned char*>(label.text);
        std::vector<Glyph> glyphs;int pen=0,left=0,top=0,right=0,bottom=0;
        while(*p) {
            const auto cp=decode(p); if(!stbtt_FindGlyphIndex(&face,cp))throw std::runtime_error("missing glyph");
            int w,h,x,y,advance,bearing;
            auto* bitmap=stbtt_GetCodepointBitmap(&face,scale,scale,cp,&w,&h,&x,&y);
            if(w&&h&&!bitmap)throw std::runtime_error("raster failure");
            stbtt_GetCodepointHMetrics(&face,cp,&advance,&bearing);
            if(w&&h){glyphs.push_back({std::vector<uint8_t>(bitmap,bitmap+w*h),pen+x,y,w,h});
                left=std::min(left,pen+x);top=std::min(top,y);right=std::max(right,pen+x+w);bottom=std::max(bottom,y+h);}
            stbtt_FreeBitmap(bitmap,nullptr);pen+=int(advance*scale+.5f);
        }
        int w=right-left,h=bottom-top;
        if(ax+w+1>width){ax=1;ay+=row+2;row=0;}
        if(w+2>width||ay+h+1>height)throw std::runtime_error("atlas overflow");
        for(const auto& g:glyphs)for(int y=0;y<g.h;y++)for(int x=0;x<g.w;x++) {
            auto& dst=atlas[(ay+g.y-top+y)*width+ax+g.x-left+x];auto src=g.pixels[y*g.w+x];
            dst=uint8_t(src+(unsigned(dst)*(255-src)+127)/255);
        }
        regions.push_back({ax,ay,w,h,left,top}); ax+=w+2;row=std::max(row,h);
    }
    // (run length, alpha) pairs; decode on menu open, release on menu close.
    std::vector<uint8_t> rle;
    for(size_t i=0;i<atlas.size();) {size_t n=1;while(n<255&&i+n<atlas.size()&&atlas[i+n]==atlas[i])++n;
        rle.push_back(uint8_t(n));rle.push_back(atlas[i]);i+=n;}
    std::ofstream out(argv[1]);
    out<<"// Generated by scripts/bake-fallback-menu.cpp; do not edit.\n"
        <<"// Rasterized from host/assets/menu.ttf (see host/assets/FONT-LICENSE.txt).\n"
        <<"#pragma once\n#include <cstdint>\nnamespace direct::fallback_atlas {\n"
        <<"constexpr unsigned width=512,height=256;\n"
        <<"struct Region { int x,y,w,h,left,top; };\nconstexpr Region regions[]={\n";
    for(auto r:regions)out<<"{"<<r.x<<","<<r.y<<","<<r.w<<","<<r.h<<","<<r.left<<","<<r.top<<"},\n";
    out<<"};\nconstexpr uint8_t rle[]={\n";
    for(size_t i=0;i<rle.size();i++){out<<unsigned(rle[i])<<",";if(i%32==31)out<<"\n";}
    out<<"\n};\n}\n";
    std::ofstream preview(argv[2],std::ios::binary);preview<<"P5\n512 256\n255\n";
    preview.write(reinterpret_cast<const char*>(atlas.data()),atlas.size());
    if(!out||!preview)return 4;
    std::printf("33 labels; atlas=512x256; RGBA=524288 bytes; embedded RLE=%zu bytes; used_height=%d\n",rle.size(),ay+row+1);
}
