#!/usr/bin/env bash
set -euo pipefail
export VITASDK=/home/qxj00/ae3-vitagl-build-20260830/vitasdk
export PATH="$VITASDK/bin:$PATH"
cmake -S host-direct -B build/native-command-port/host -DDIRECT_BUILTIN_EFFECTS=ON -DDIRECT_BUILTIN_PROBE=ON -DDIRECT_CAPUNLOCKER=ON -DDIRECT_DEFERRED_FINISH_CANDIDATE=ON -DDIRECT_DRAWLIST_REUSE_CANDIDATE=OFF -DDIRECT_DRAW_AUDIT=OFF -DDIRECT_FULL_COVER_CANDIDATE=OFF -DDIRECT_GXM_PROBE=OFF -DDIRECT_HEAP_DIAGNOSTICS=ON -DDIRECT_HISTORY_CANDIDATE=OFF -DDIRECT_MESSAGE_CANDIDATE=OFF -DDIRECT_MESSAGE_INPUT_CANDIDATE=OFF -DDIRECT_NUMERIC_TWEEN_CANDIDATE=OFF -DDIRECT_OPACITY_SCAN_BENCH=OFF -DDIRECT_REBUILD_AUDIT_CANDIDATE=OFF -DDIRECT_REBUILD_PROFILE_CANDIDATE=OFF -DDIRECT_RESOURCE_LEDGER=ON -DDIRECT_REUSE_HISTORY_CANDIDATE=OFF -DDIRECT_SCENE_ORDER_CANDIDATE=OFF -DDIRECT_SEMANTIC_CONTROLS=ON -DDIRECT_TEXT_EPOCH_CANDIDATE=ON -DDIRECT_TEXT_SYNC_PROFILE_CANDIDATE=OFF -DDIRECT_VISIBLE_CLIP_CANDIDATE=OFF -DART3_DIRECT_VERSION=01.10 -DART3_DIRECT_CORE_LIBRARY=/mnt/f/WorkSpaceAI2/art3m1s-psv-gxm/build/native-command-port/libart3m1s_core.a
cmake --build build/native-command-port/host --target art3m1s_direct.vpk-vpk -j2
