param([string]$CompilerDirectory)
$ErrorActionPreference = 'Stop'
$workspacePath = Split-Path $PSScriptRoot -Parent
if (-not $CompilerDirectory) {
    $CompilerDirectory = Join-Path $workspacePath '.tools/sony-shader-3.570/sdk/host_tools/bin'
}
$compilerPath = Join-Path $CompilerDirectory 'psp2cgc.exe'
$inspectorPath = Join-Path $CompilerDirectory 'psp2cgnm.exe'
$sourcePath = Join-Path $workspacePath 'tests/rule_shader/rule_transition_f.cg'
$outputDirectory = Join-Path $workspacePath 'build/rule-shader-offline'
New-Item -ItemType Directory -Force $outputDirectory | Out-Null
$outputPath = Join-Path $outputDirectory 'rule_transition_f.gxp'
$compilerPath = (Resolve-Path -LiteralPath $compilerPath).Path
$inspectorPath = (Resolve-Path -LiteralPath $inspectorPath).Path
# The compiler's output hash depends on the input path spelling. Keep relative
# source/output arguments stable when the checkout is moved to another machine.
$compileArgs = @('-profile', 'sce_fp_psp2', '-O1', '-nofastmath', '-bestprecision', '-nofastint', '-o', 'build/rule-shader-offline/rule_transition_f.gxp', 'tests/rule_shader/rule_transition_f.cg')
Push-Location $workspacePath
try {
    & $compilerPath @compileArgs 2>&1 | Tee-Object -FilePath (Join-Path $outputDirectory 'compile.log')
    if ($LASTEXITCODE -ne 0) { throw "Shader compilation failed: $LASTEXITCODE" }
} finally { Pop-Location }
$parameters = & $inspectorPath $outputPath 2>&1
if ($LASTEXITCODE -ne 0) { throw "Shader inspection failed: $LASTEXITCODE" }
$parameters | Set-Content (Join-Path $outputDirectory 'parameters.txt')
$parameterText = $parameters -join "`n"
foreach ($expected in @('uni frag float4 11 0 default', 'smp oldFrame 2D none 4 0', 'smp ruleMap 2D none 4 1')) {
    if (-not $parameterText.Contains($expected)) { throw "Unexpected shader binding; missing: $expected" }
}
$version = (& $compilerPath -version 2>&1) -join "`n"
$manifest = [ordered]@{
    compiler_version = $version
    compiler_sha256 = (Get-FileHash -LiteralPath $compilerPath -Algorithm SHA256).Hash
    source_sha256 = (Get-FileHash -LiteralPath $sourcePath -Algorithm SHA256).Hash
    gxp_sha256 = (Get-FileHash -LiteralPath $outputPath -Algorithm SHA256).Hash
    arguments = $compileArgs
    bytes = (Get-Item -LiteralPath $outputPath).Length
    parameter_check = 'passed'
    gpu_render_check = 'not_run'
}
$manifest | ConvertTo-Json -Depth 5 | Set-Content (Join-Path $outputDirectory 'manifest.json')
$gxpBytes = [IO.File]::ReadAllBytes($outputPath)
$gxpLines = for ($i = 0; $i -lt $gxpBytes.Length; $i += 12) {
    $last = [Math]::Min($i + 11, $gxpBytes.Length - 1)
    '    ' + (($gxpBytes[$i..$last] | ForEach-Object { '0x{0:x2}' -f $_ }) -join ', ') + ','
}
$sourceLiteral = ConvertTo-Json -InputObject ([IO.File]::ReadAllText($sourcePath)) -Compress
$header = @(
    '// Generated by scripts/build-rule-shader.ps1; do not edit.',
    "// Source SHA256: $($manifest.source_sha256)",
    "// GXP SHA256: $($manifest.gxp_sha256)",
    '#pragma once',
    'static const unsigned char art3m1s_rule_gxp[] __attribute__((aligned(4))) = {',
    ($gxpLines -join "`n"),
    '};',
    "static const char art3m1s_rule_cg[] = $sourceLiteral;"
) -join "`n"
[IO.File]::WriteAllText((Join-Path $workspacePath 'vendor/borealis/library/include/borealis/extern/nanovg/art3m1s_rule_shader.h'), $header)
$manifest | ConvertTo-Json -Depth 5
