"""Bundle the audited fixed-wrapper effects; no runtime compiler is required.
Sources are read-only. Run compile-external-shaders.py first if rebuilding GXP.
"""
from pathlib import Path
import json, struct, shutil

ROOT=Path(__file__).resolve().parents[1]
def main():
    src=ROOT/'build/external-shaders/compiled/toshiue/system/shader/pc'
    dst=ROOT/'shaders/artemis-pc'
    core=ROOT/'build/heap-audit/controls-source/core/src/backend/gxm'
    dst.mkdir(parents=True,exist_ok=True)
    entries=[]; probe=[]
    for p in sorted(src.glob('*.agxp')):
        data=p.read_bytes(); m,b=struct.unpack_from('<II',data,4)
        meta=json.loads(data[12:12+m]); gxp=data[12+m:]
        assert len(gxp)==b and gxp[:4]==b'GXP\0'
        name=p.name.split('.')[0]
        shutil.copyfile(p,dst/p.name)
        cg=p.with_suffix(p.suffix+'.cg').read_text()
        (dst/(name+'.cg')).write_text('\n'.join(line.rstrip()for line in cg.splitlines())+'\n')
        entries.append(dict(name=name,source_hash=meta['source_hash'],bytes=b,uniforms=meta['uniforms']))
        probe.append('static const unsigned char bundled_'+name+'[]={'+','.join(map(str,gxp))+'};')
        probe.append('static const BundledUniform uniforms_'+name+'[]={'+','.join('{"%s",%d,%d}'%(u['name'],u['offset'],u['count']) for u in meta['uniforms'])+'};')
    assert len(entries)==31
    (dst/'manifest.json').write_text(json.dumps(entries,indent=2)+'\n')
    module='// Generated by scripts/bundle-artemis-shaders.py. Exact source identity only.\npub(super) fn lookup(hash:&str)->Option<(&\'static str,&\'static [u8])>{Some(match hash {\n'
    for e in entries:module+='"%s"=>("%s",include_bytes!("bundled/%s.hlsl.agxp")),\n'%(e['source_hash'],e['name'],e['name'])
    module+='_=>return None,\n})}\n'
    (dst/'bundled_effects.rs').write_text(module)
    (core/'bundled').mkdir(exist_ok=True)
    for p in dst.glob('*.agxp'):shutil.copyfile(p,core/'bundled'/p.name)
    shutil.copyfile(dst/'manifest.json',core/'bundled/manifest.json')
    shutil.copyfile(dst/'bundled_effects.rs',core/'bundled_effects.rs')
    probe.append('static const BundledEntry bundledEntries[]={')
    for e in entries:
        n=e['name'];probe.append('{"%s",bundled_%s,sizeof(bundled_%s),uniforms_%s,sizeof(uniforms_%s)/sizeof(BundledUniform)},'%(n,n,n,n,n))
    probe.append('};')
    (ROOT/'host-direct/src/bundled_probe_data.hpp').write_text('// Generated; diagnostic builds only.\n'+'\n'.join(probe)+'\n')
    print('Bundled 31 unique programs covering 51 source files;',sum(e['bytes'] for e in entries),'GXP bytes')
if __name__=='__main__':main()
