uniform sampler2D samplerFore : TEXUNIT0;
uniform sampler2D samplerMask : TEXUNIT1;
uniform sampler2D samplerUser : TEXUNIT3;
uniform float4 art_clip;
uniform float  alpha;
uniform float3 colorMultiply;
uniform float  maskTransitionVague;
uniform float  maskTransitionStep;
uniform float  weights[8];
uniform float  width;
float4 main(float2 texCoord1:TEXCOORD0,float4 tint:COLOR0,float2 pixel:TEXCOORD1):COLOR {
float2 texCoord0=texCoord1; float4 result=float4(0,0,0,0);

	float4 fore = tex2D(samplerFore, texCoord1) * weights[0];
	float4 mask = tex2D(samplerMask, texCoord1);
	float mask_a = mask.a;

	fore += tex2D(samplerFore, texCoord1 + float2(width *  1.0, 0.0)) * weights[1];
	fore += tex2D(samplerFore, texCoord1 + float2(width * -1.0, 0.0)) * weights[1];
	fore += tex2D(samplerFore, texCoord1 + float2(width *  2.0, 0.0)) * weights[2];
	fore += tex2D(samplerFore, texCoord1 + float2(width * -2.0, 0.0)) * weights[2];
	fore += tex2D(samplerFore, texCoord1 + float2(width *  3.0, 0.0)) * weights[3];
	fore += tex2D(samplerFore, texCoord1 + float2(width * -3.0, 0.0)) * weights[3];
	fore += tex2D(samplerFore, texCoord1 + float2(width *  4.0, 0.0)) * weights[4];
	fore += tex2D(samplerFore, texCoord1 + float2(width * -4.0, 0.0)) * weights[4];
	fore += tex2D(samplerFore, texCoord1 + float2(width *  5.0, 0.0)) * weights[5];
	fore += tex2D(samplerFore, texCoord1 + float2(width * -5.0, 0.0)) * weights[5];
	fore += tex2D(samplerFore, texCoord1 + float2(width *  6.0, 0.0)) * weights[6];
	fore += tex2D(samplerFore, texCoord1 + float2(width * -6.0, 0.0)) * weights[6];
	fore += tex2D(samplerFore, texCoord1 + float2(width *  7.0, 0.0)) * weights[7];
	fore += tex2D(samplerFore, texCoord1 + float2(width * -7.0, 0.0)) * weights[7];
	fore.a *= mask_a * alpha;

	result = fore;

float cover=step(art_clip.x,pixel.x)*step(art_clip.y,pixel.y)*(1-step(art_clip.z,pixel.x))*(1-step(art_clip.w,pixel.y));
return result*cover;
}
