uniform sampler2D samplerFore : TEXUNIT0;
uniform sampler2D samplerMask : TEXUNIT1;
uniform sampler2D samplerUser : TEXUNIT3;
uniform float4 art_clip;
uniform float  alpha;
uniform float3 colorMultiply;
uniform float  maskTransitionVague;
uniform float  maskTransitionStep;
uniform float  centerx;
uniform float  centery;
uniform float  radius;
uniform float  ratio;
uniform float  dark;
float4 main(float2 texCoord1:TEXCOORD0,float4 tint:COLOR0,float2 pixel:TEXCOORD1):COLOR {
float2 texCoord0=texCoord1; float4 result=float4(0,0,0,0);


	float4 mask = tex2D(samplerMask, texCoord1);
	float mask_a = mask.a;


	float y = (texCoord1.y - 0.5) * ratio + 0.5;
	float2 zoomuv = float2(texCoord1.x, y);


	float2 ct = float2(centerx, centery);


	float dist = distance(ct, zoomuv);
	float perra = (1.0 - radius) * 0.5;
	float rbase = dist - radius;
	float r1 = rbase - perra * 2.0;
	float r2 = rbase + perra;

	float range = 1.0 - smoothstep(r1, r2, 0.0);
	float distx = lerp(1.0 - range, 1.0, step(range, 0.0));
	float4 fore = tex2D(samplerFore, lerp(ct, texCoord1, distx));


	fore.rgb *= dark;


	fore.a *= mask_a * alpha;

	result = fore;

float cover=step(art_clip.x,pixel.x)*step(art_clip.y,pixel.y)*(1-step(art_clip.z,pixel.x))*(1-step(art_clip.w,pixel.y));
return result*cover;
}
