uniform sampler2D samplerFore : TEXUNIT0;
uniform sampler2D samplerMask : TEXUNIT1;
uniform sampler2D samplerUser : TEXUNIT3;
uniform float4 art_clip;
uniform float  alpha;
uniform float3 colorMultiply;
uniform float  maskTransitionVague;
uniform float  maskTransitionStep;
uniform float  centerx;
uniform float  centery;
uniform float  steps;
uniform float  dost;
float4 main(float2 texCoord1:TEXCOORD0,float4 tint:COLOR0,float2 pixel:TEXCOORD1):COLOR {
float2 texCoord0=texCoord1; float4 result=float4(0,0,0,0);


	float4 mask = tex2D(samplerMask, texCoord1);
	float mask_a = mask.a;


	float s = (1.0 - steps) / 2;
	float x = (texCoord1.x - centerx) / steps + centerx;
	float y = (texCoord1.y - 0.5) / (1.0 - (x - centerx) * s) + 0.5;

	float2 uv = float2(x, y);
	float4 fore = tex2D(samplerFore, uv);


	fore.a *= step(1.0 - x, 1.0) * step(x, 1.0);

	fore.a *= smoothstep(-dost, 0.0, y) * smoothstep(0.0, dost, 1.0 - y);


	fore.a *= mask_a * alpha;

	result = fore;

float cover=step(art_clip.x,pixel.x)*step(art_clip.y,pixel.y)*(1-step(art_clip.z,pixel.x))*(1-step(art_clip.w,pixel.y));
return result*cover;
}
